### ISSUE TITLE
Prevent name collisions in the intermediate representation, even across types

### ISSUE THREAD

**Issue by maxqchen** [manifold-lang/manifold#134]
Because there's a different table for each type map (port, node, etc), multiple type definitions may end up having the same name.

**Comment by lucaswoj** [comment]
It doesn't really matter if we have a name collision in the IR. Everything is statically typed and doesn't need to be super human readable.

**Comment by maxqchen** [comment]
It does if I'm trying to rebuild the IR from the output and there are references to defined types. Right now we differentiate between types by using the object reference in java, which does not exist anymore.

**Comment by lucaswoj** [comment]
If types are ambiguous, I think I'd prefer to refactor the intermediate so that types are not ambiguous. Working with the default JSON output was a great MVP but we're going to have start customizing that at some point.

**Comment by maxqchen** [comment]
I'm not referring to the GSON output - that will definitely have to change. I'm referring to the intermediate itself.

**Comment by maxqchen** [comment]
Wrong button, my bad. Meant to comment. 

Yes, this is not an output issue, it is an intermediate issue. I think it's engrained in the fact that our attributes are referring to the generic TypeValue instead of the user defined type.

**Comment by lucaswoj** [comment]
I think I understand. Sounds good :-) I support this change!
