### ISSUE TITLE
Write a first draft of the WHDL intermediate specification

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#14]

**Comment by mtrberzi** [comment]
I've made some progress on the wiki at https://github.com/whdl/whdl/wiki/Intermediate-Language-Specification although note that as of this writing this doesn't tell you **how** to generate code from this spec, only **what** the spec describes. Also, there may be some revisions as I figure out what I was actually trying to accomplish with respect to certain statements like `sequence`.

**Comment by lucaswoj** [comment]
Thanks Murphy! Some thoughts:
- I’m not sure what the difference between a module and a component is — they’re both rather vague words describing a unit of code. Whats the difference between them? Do we need both? Please clarify this in the documentation. Perhaps consider different names.
- Could you describe how interfaces work? A quick example would help me understand. I assume this is just a declaration of io pins but I’m unsure.
- The different types of statements are not explained anywhere. I don’t know what a “ci” or “reg” or “sequence” or “inst” statement is. Please clarify this in the documentation. Perhaps consider longer more descriptive names for these tokens (they’ll almost always be machine-generated anyway)

**Comment by lucaswoj** [comment]
@MurphEngineer Did you see my feedback here? Would love to get the backend compiler up and running soon!

**Comment by mtrberzi** [comment]
@lucaswoj I'll have a chance to improve the stuff I wrote in a bit. I just want to get that last pull request in and do a bit of work on exception testing.
