### ISSUE TITLE
Convince CI server to rebuild outstanding pull requests when master is changed

### ISSUE THREAD

**Issue by mtrberzi** [manifold-lang/manifold#148]
As of this writing, the build has been broken twice because pull requests that built successfully in the past resulted in errors in master when merged. If the CI server rebuilt pull requests whenever master changed, errors of this type would be much easier to catch during code review before the branch is merged.

**Comment by lucaswoj** [comment]
You need to rebase your own branch into master and then do a push -f. There are good reasons Travis acts this way.
