### ISSUE TITLE
AST-level compiler prototype

### ISSUE THREAD

**Issue by mtrberzi** [manifold-lang/manifold#2]
Implement the "core subset" of WHDL given abstract syntax trees (ASTs) for the various syntactic constructs. This will allow us to prototype the compiler without a concrete specification for the language (and without a lexer/parser).

**Comment by lucaswoj** [comment]
This task is pretty broad. Do you think you could break it down into smaller pieces? Perhaps some of them might include
- Define all AST node types and their attributes
- Document the high level architecture of the compiler's AST module
- Create classes and tests for all AST node types
