### ISSUE TITLE
Create FunctionValue and FunctionTypeValue classes

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#28]
This is a big project. 
- functions can be overloaded arbitrarily many times with different arguments, assigned into the same conceptual value.
- primitive functions may by executable at compiletime, runtime, or both.

The interface might look like
#### FunctionTypeValue

``` java
class FunctionTypeValue extends TypeValue {}
```
#### UnspecifiedFunctionTypeValue

Represents the generic `Function` type arbitrarily many overloaded input/output types.

This class should have a singleton instance.

``` java
class UnspecifiedFunctionTypeValue extends FunctionTypeValue {}
```
#### SpecifiedFunctionTypeValue

Represents a function with one implementation for specific input and output types.

``` java
class SpecifiedFunctionTypeValue extends org.whdl.frontend.FunctionTypeValue {
  TypeValue inputType;
  TypeValue outputType;
}
```
#### FunctionValue

``` java
class FunctionValue extends Value {
  Value evaluate(Value input);

  public abstract class Implementation {
    Implementation(Scope);
    abstract TypeValue getInputTypeValue();
    abstract TypeValue getOutputTypeValue();
    abstract Value evaluate(Value input);
    boolean isCompiletimeEvaluable();
    boolean isRuntimeEvaluable();
  }

  class CompositeImplementation extends Implementation {
    Set<org.whdl.frontend.Statement> getBody();
  }

  abstract class PrimitiveImplementation extends Implementation {}
}
```

**Comment by TysonAndre** [comment]
some comments on interfaces:

FunctionTypeValue should be an abstract class?

getBody() should return a list of statements, not a set (I think our language wants things executed in order to create hardware?)

you don't have an interface for adding implementations to a FunctionValue yet.

What things will be primitiveImplementations? How will they be overridden/prevented from being overridden.

**Comment by lucaswoj** [comment]
You're right, `FunctionTypeValue` should be an abstract class. Or we should just scrap the `UnspecifiedFunctionTypeValue` and `SpecifiedFunctionTypeValue` classes.

The order of statements in whdl is strictly arbitrary -- everything needs to run concurrently, conceptually.

I will add that interface as I build the class. This interface is not complete. 

`PrimitiveImplementations` include functions like "logical and" which are implemented as physical hardware on the board and written directly in Java within the compiler. We can mark those classes as final, if you'd like that safety.
