### ISSUE TITLE
Create a File class

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#29]
The `File` class represents a single file of source code. Each file belongs to a namespace has its own scope into which it may import values from other namespaces and export members to its namespace.

The interface might look like

``` java
class File {
  Namespace getNamespace();
  Set<Expression> getBody();

  Scope getScope();

  // Trigger the formal verification pass
  void verify();

  class NamespaceImport {
    Enum Type = {whitelist, blacklist};
    Type type;
    NamespaceIdentifier namespace;
    Set<VariableIdentifier, String> variables;
  }
  ArrayList<Import> namespaceImports;

  Map<VaribleIdentifier, String> namespaceExports;
}
```

**Comment by lucaswoj** [comment]
Maybe we want to call this `CompilationUnit`

**Comment by TysonAndre** [comment]
Same as before: `List<Expression> getBody()`, they are in order

**Comment by lucaswoj** [comment]
I disagree. I think we ought to forget about the order statements as early as possible because everything will execute concurrently, in theory.

**Comment by lucaswoj** [comment]
I should also point out that Murphy has subsumed this task into his pull request #38
