### ISSUE TITLE
Create EnumTypeValue and EnumValue classes

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#30]
Not sure _exactly_ how this will work. Maybe this interface is good?
#### EnumTypeValue

``` java
abstract class EnumTypeValue extends TypeValue {}
```
#### UnspecifiedEnumTypeValue

``` java
class UnspecifiedEnumTypeValue extends EnumTypeValue {}
```
#### SpecifiedEnumTypeValue

``` java
class SpecifiedEnumTypeValue extends EnumTypeValue {
  class Value {
    String name;
    Value value;
  }

  Set<EnumTypeValue::Value> values;
  TypeValue valuesType;
}
```
#### EnumValue

``` java
class EnumTypeValue extends TypeValue {
  EnumTypeValue::Value getValue();

  // Make sure the value belongs to this enum's type
  void verify();
}
```

**Comment by maxqchen** [comment]
Our enums are allowed to map to arbitrary values? I was under the impression that it would map strictly to integers?

**Comment by lucaswoj** [comment]
We agreed that each enum type had values of one particular variable type -- not necessarily an integer. Not sure if I have that in writing or not :-/
