### ISSUE TITLE
Decide on a consistent test naming convention and backport the codebase.

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#45]
http://stackoverflow.com/questions/96297/what-are-some-popular-naming-conventions-for-unit-tests

**Comment by mtrberzi** [comment]
At minimum, it's probably not necessary to call methods "test*", we have the `@Test` annotation for that.

**Comment by mtrberzi** [comment]
I'm a fan of `MethodName_StateUnderTest` or `MethodName_StateUnderTest_ExpectedBehaviour`

**Comment by lucaswoj** [comment]
Sounds like we've decided on a naming convention, this needs to
- [ ] be documented
- [ ] be implemented in the existing test files
