### ISSUE TITLE
Write unit tests for the exceptions

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#52]
Do fuzzy matching on messages (ie assert that the message for multiple assignment contains the variable identifier).

**Comment by mtrberzi** [comment]
I'll take this one on...

**Comment by lucaswoj** [comment]
Go for it! Thanks!

**Comment by mtrberzi** [comment]
Hmm, we'll need some better "toString()" methods on some of our TypeValue and Value classes...I'll open a new issue for that and do my best with this (the tests will still be okay)
