### ISSUE TITLE
Convert the BooleanValue and BooleanTypeValue classes into subclasses of EnumValue and EnumTypeValue

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#56]

**Comment by lucaswoj** [comment]
Depends on #30

**Comment by lucaswoj** [comment]
@maxqchen Do you think you could tackle this next, now that your pull request has landed?

**Comment by maxqchen** [comment]
I was under the impression that I should finish up the reading part for the IR as well. But yes I can add this to my queue after that is done.

**Comment by lucaswoj** [comment]
Lets say _next_ in the broad sense :wink: Thanks!
