### ISSUE TITLE
Clean up package structure

### ISSUE THREAD

**Issue by maxqchen** [manifold-lang/manifold#61]
The number of classes in the syntax tree package is getting a bit nasty. I propose we make sub packages to better organize our files. Something like syntaxtree.tuple, syntaxtree.enums, syntaxtree.exceptions and so forth.

**Comment by lucaswoj** [comment]
Why do you think the number of classes is a problem? Do you think the project would be much easer to navigate with many more "sub" namespaces? I feel like having fewer big namespaces around each major "problem domain" makes for the easiest navigation as a developer.

**Comment by maxqchen** [comment]
Since we're not using package protected this is only an aesthetics preference. Having all the files for one thing grouped together makes working with them easier, imo. From the top level, instead of looking at 20-30 files we can just look at 5-6 packages.

**Comment by lucaswoj** [comment]
I feel like this increases the conceptual complexity of the project (and likely the amount of clicking and typing I’ll have to do) but I can see this is a personal preference. What do you think, @MurphEngineer and @TysonAndre?

**Comment by mtrberzi** [comment]
I think subpackages isn't a bad thing. Each top-level package could be a major problem domain, like you said (e.g. "syntaxtree", "typesystem", "frontend", "backend", or whatever we decide...) but without subpackages, dumping all of the files into the same level of these (soon-to-be if not already) large packages will make navigating the project much more complicated than it needs to be.

...is my opinion, anyway. Refactoring is cheap; if things get complicated, it shouldn't be too difficult to reorganize as the project grows.

**Comment by lucaswoj** [comment]
I usually navigate by searching filename so I don't see this pain point. Maybe industry has ruined me... Most projects I've worked on have erred on the side of fewer namespaces.

Anyway, @maxqchen feel free to take the helm on this one!

**Comment by lucaswoj** [comment]
Playing devil's advocate again, if we have a package for every type, almost all of them will have exactly two classes in them (a `Value` class and a `TypeValue` class) -- classes that would be alphabetically next to each other anyway in a sorted list. But now there are 50% more "entities" in the project and all the cognitive overhead of navigating around these subpackages. 

I guess I'm advocating more of a "wait and see" approach. I've worked on really huge projects with very few namespaces and had no trouble navigating them.

**Comment by lucaswoj** [comment]
Ok, so here's the thing: I think adding more sub-namespaces is a trade-off: you gain a certain amount of organization of classes in exchange for having to think about all these extra packages. I think the best way to go about this avoiding premature optimization is to wait until things start getting painful and then group classes into broad packages -- say `types` and `expressions`. When that starts getting a little more painful we might break each of those into smaller subpackages.
