### ISSUE TITLE
Design intermediate language

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#66]
We are revamping our intermediate language specification to be able to handle more general "things"

**Comment by mtrberzi** [comment]
I think I have a feasible design...I'll post some notes later on, or maybe just implement it in objects and throw it into a pull request!

**Comment by mtrberzi** [comment]
Forgot to associate #70

**Comment by mtrberzi** [comment]
I think #74 has almost completely resolved this modulo some outstanding small issues, closing for now.
