### ISSUE TITLE
Brainstorm new language name

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#68]
Must have available domain names!

**Comment by mtrberzi** [comment]
EDGE sounds like a sharp name; we could backronym it to something like "Engineering Designs with Graph Elaboration" or the like...and it's a graph theory joke too.

**Comment by lucaswoj** [comment]
It doesn't have to be a backronym. It just has to be a good name.
- no existing languages with the same name
- some kind of domain name availability 
- memorable
- captures the essence of the project 

"Edge" is good.

**Comment by mtrberzi** [comment]
Manifold turned out to be better!
