### ISSUE TITLE
Integrate with coveralls.io for code coverage stats

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#69]
This will probably do all the heavy-lifting for us! https://github.com/trautonen/coveralls-maven-plugin

**Comment by mtrberzi** [comment]
I checked out the site, and either I'm missing something about organizations, or only the original creator of the repo can add it, so @lucaswoj this one's for you

**Comment by lucaswoj** [comment]
I think it'll take a little finagling but might be as simple as following [these instructions](https://github.com/trautonen/coveralls-maven-plugin) (gradle is built atop Maven)

**Comment by lucaswoj** [comment]
I'll tackle this one in the next few days!

**Comment by mtrberzi** [comment]
Our Coveralls site hasn't been updated since your initial commit that added support (i.e. coverage for the latest stuff in master isn't visible yet). Could you look into this?
