### ISSUE TITLE
Remove the notion of "connection types"

### ISSUE THREAD

**Issue by mtrberzi** [manifold-lang/manifold#73]
Everything that can be expressed by a connection type now could be done by a constraint. Keep the intermediate simple and remove connection types for now.

**Comment by mtrberzi** [comment]
Hold on, I have a counterexample. Consider two microfluidic sensor nodes. Clearly they can be connected together by a fluid connection. But they can also be connected by a digital circuit connection as part of the control plane. However, because both are just connections from sensor-node to sensor-node, these connections cannot be differentiated without connection types (or a relatively pointless constraint that does exactly the same thing as a connection type).

**Comment by lucaswoj** [comment]
But, in your counterexample, we can still infer the connection type based on the endpoint types. Furthermore, lets make the simplifying assertion that connections can only connect endpoints of the same type (`digital -> digital`, `fluid -> fluid`)

**Comment by mtrberzi** [comment]
Okay, this is fine assuming connections can only connect endpoints/ports of the same type.

**Comment by mtrberzi** [comment]
The type is then "implicit" in the sense that we can check it by examining the type of the endpoints being connected.

**Comment by mtrberzi** [comment]
The intermediate does not even need to keep track of this type explicitly, so the "connection type" thing can just go away.

**Comment by mtrberzi** [comment]
Wait, I've thought of something else. Connections can have attributes. Right now the connection type contains all the information about the attribute names and types that can be put onto a given connection. If we lose connection types, we also lose connection attributes. I still agree that connections should only connect ports of the same type, but I do not see a more elegant way to deal with connection attributes.

**Comment by lucaswoj** [comment]
Ok. Let's have connection types and define ports in terms of connection types. Cool?—

**Comment by mtrberzi** [comment]
What do you mean by "define ports in terms of connection types"? Does that just mean that "connections only connect ports of the same type", or do ports need to know something else about connections in order to exist?

**Comment by lucaswoj** [comment]
Instead of having connections of type "connection type" and ports of type "port type"...

We have connections of type "connection type" and ports of type "connection type" 
—

**Comment by mtrberzi** [comment]
No again, for the same reason. Ports may have a distinct set of attributes from connections. And semantically, it doesn't make any sense for a thing called a `Port` to be anything other than a `PortType`.

**Comment by lucaswoj** [comment]
Semantic naming issues aside, I didn't realize that both connections and ports may have attributes. Are you certain that this is nescessary? What is the use case for assigning an attribute to a port? —

**Comment by lucaswoj** [comment]
What if every port has a "commectiom_type" attribute? —

**Comment by mtrberzi** [comment]
Okay, every port can have a "connection_type" attribute, that is okay. One example of assigning an attribute to a port might be this -- consider a pipe network in fluid dynamics. We connect port A to port B with a pipe. Now, we might care about the diameter of port A and port B, which need not be the same. The diameter of the port belongs to the port and not to the connection, so it should be an attribute of the port.

**Comment by lucaswoj** [comment]
Huh. Complex. You've seen my side of the argument. I trust you to make this decision. —

**Comment by mtrberzi** [comment]
I think the best solution is the most general one, which corresponds to having Connection Types and Port Types. There may be cases we have not considered yet where describing these circuits is laborious or impossible without these things. I will think more about the relationship between ports and connections before I make a decision.

**Comment by lucaswoj** [comment]
Yeah. There is some conceptual crossover but I think you've made the case for a full separation. —
