### ISSUE TITLE
Prepare for Midterm Demo

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#75]
- [x] Prepare something to present as a prototype
- [x] Prepare to defend our compliance with the [Joel Test](http://www.joelonsoftware.com/articles/fog0000000043.html)
- [x] Prepare to present our system architecture
- [x] Prepare to present productivity metrics (GitHub does a pretty good job of this for us)

**Comment by mtrberzi** [comment]
We did this at the Yelp demo and received a grade of A+!
