### ISSUE TITLE
Create schedule for semester

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#77]
We should have something interesting to show at the midterm demo and a final demo.

**Comment by mtrberzi** [comment]
Let's import the one we just used for the Yelp demo for now.

**Comment by lucaswoj** [comment]
![image](https://cloud.githubusercontent.com/assets/281306/3097788/3bbd7ad8-e5e3-11e3-988b-0f0a4657e504.png)

**Comment by lucaswoj** [comment]
Here's a screencap. This should probably go into the wiki somewhere.
