### ISSUE TITLE
Fill in Joel Test Compliance wiki page

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#78]
https://github.com/manifold-lang/manifold/wiki/Joel-Test-Compliance

**Comment by mtrberzi** [comment]
I just ticked off two items. Five more to go.

**Comment by lucaswoj** [comment]
Thanks Murph. I filled in most other sections, pending two for which there are outstanding questions:

> ### What is your iteration plan?
> 
> _I don't know what this means, exactly._
> 
> ### Do you have a specifications document?
> 
> _If we have a formal writeup of our frontend language spec, we could argue that this suffices._
