### ISSUE TITLE
Create a consistent abstraction for (key-value) attributes

### ISSUE THREAD

**Issue by mtrberzi** [manifold-lang/manifold#81]

**Comment by mtrberzi** [comment]
Tyson, you brought this issue up in my last pull request, would you like to tackle it?

**Comment by TysonAndre** [comment]
Sounds good. 

#80 seems related, so is there anything apart from changing unit tests I'd need to think about if I added that?
Or should I just leave out type checking in the change, and create an AttributeSet.
