### ISSUE TITLE
Decide on repository branching strategy

### ISSUE THREAD

**Issue by mtrberzi** [manifold-lang/manifold#84]
This one seems to be popular (master+develop branch strategy): http://nvie.com/posts/a-successful-git-branching-model/

**Comment by lucaswoj** [comment]
I like that protocol. However, I think something that complex is overkill until we start having external users. Lets just stick with feature branches merged into master via pull requests for the duration of our FYDP.

**Comment by mtrberzi** [comment]
Fair enough, let's stick with what works.
